### ISSUE TITLE
Which node version is needed?

### ISSUE THREAD

**Issue by TonyFeestneus** [svrooij/node-xiaomi2mqtt#1]
Now on 4.4.2 but getting lots of errors. Thanks

**Comment by svrooij** [comment]
Developed on 6.11.2 (the latest LTS version)

**Comment by TonyFeestneus** [comment]
Thanks. Did you try it with Aqara temperature humidity?

**Comment by svrooij** [comment]
This library uses [node-lumi-aqara](https://github.com/marvinroger/node-lumi-aqara/blob/master/src/lib/gateway.js) for communicating with the gateway, and both me and the Developer of that library don't own a temp/humidity sensor. So this is not yet implemented.

But if you could provide me with one, I will update the application. [buy me own](https://✌️.tk/beer). Or send me yours 😝

**Comment by TonyFeestneus** [comment]
I am much like you: I like to tinkle with this myself :)

I see my Aqara temp sensor, but can't get any data out of it.
not handled: {"cmd":"read_ack","model":"","sid":"158d0001a4b661","short_id":14079,"data":"{}"}

Is there anything you can do to point me in the right direct?

**Comment by TonyFeestneus** [comment]
UPDATE: I did choose for a firmware upgrade but I guess it did not upgrade. Did it again, works now.

Couple issues:
1. line 89 in lumi-aqara/src/lib/gateway.js needs commenting or changing, because this makes an error when value is updated

2. are these values updated realtime? So if I were to buy a motion sensor, would it actually send a mqtt message immediately so I can switch on a light based on message?
You say:
_The statuses of the devices are multicasted over the network if you enbaled this (you SHOULD!!). So all the updates to mqtt are near instant._
Where to enable?

3. if you want, I can send you data that sensor puts out so you can add it to your code

4. most importantly: I mistakenly (?) installed nodejs next to node. So now I have node 4.4.2, and nodejs 8.2.1. I can run some files with node filename.js, if it needs newer node like your project, I can run it with nodejs filename.js.
So they are somewhat separated, but does not feel reel good to me. What do you think?

**Comment by svrooij** [comment]
Things you need to change to add extra sensors:
- change the interface library, look at the the pull request about the error.
- add some subdevice
- change this library check out [this sction](https://github.com/svrooij/node-xiaomi2mqtt/blob/master/index.js#L109). 

The magnet sensors are updated within like 100ms but it might depend on your own network.

I would not install 2 versions of node on the same computer. 4.x is terribly old and the newer versions should be backward compatible (to some point)

**Comment by TonyFeestneus** [comment]
Thanks. Would you recommend nodejs or node?

**Comment by svrooij** [comment]
at my computer it is installed as node.... That is the default. And I would recommend using at least the latest LTS (6.*) or the last version... Version 4.* is quite old.

Moving the other sensors to a new issue.
