### ISSUE TITLE
Couple of issues with "xiaomi/connected" topic

### ISSUE THREAD

**Issue by mikeS7** [svrooij/node-xiaomi2mqtt#10]
mosquitto broker treats zero value as empty, on disconnect "xiaomi/connected" topic disappeared instead changing value to 0.
Type of WILL message is number at line https://github.com/svrooij/node-xiaomi2mqtt/blob/638450a70fe763343aa28f1f89e239cf571ace57/src/bridge.js#L33
I think it should be text:
message: "0",

also at line https://github.com/svrooij/node-xiaomi2mqtt/blob/638450a70fe763343aa28f1f89e239cf571ace57/src/bridge.js#L188 gateways.length is 0, because gateways is an object, not an array. Object.keys can be used:
Object.keys(gateways).length

**Comment by svrooij** [comment]
Are you sure about the gateways field? I always thought that this would create an array https://github.com/svrooij/node-xiaomi2mqtt/blob/638450a70fe763343aa28f1f89e239cf571ace57/src/bridge.js#L11

You can threat non-existing connected topic as not connected. If you shutdown the bridge isn’t is nicer to remove the topic?

**Comment by mikeS7** [comment]
According [mqtt-smarthome architecture](https://github.com/mqtt-smarthome/mqtt-smarthome/blob/master/Architecture.md#connected-status) architecture topic should be changed to "0".

Yes, you initialized gateways as array, but use it as associative array which is an object, more info
[Length of a javascript associative array](https://stackoverflow.com/questions/10563251/length-of-a-javascript-associative-array)

**Comment by svrooij** [comment]
But of the specs say I have to set is to the integer 0, (and mosquitto is handling that as null and thus removing it). How would you think I should fix it? Since “0” isn’t an integer.

You’re right about the array length. It is only done this way to a quick fix for multiple gateways. (Really recent). Will create a new fix tomorrow

**Comment by mikeS7** [comment]
I think 0, 1, 2 should be the same type, but we have:
0 as integer
'1' and '2' as string
https://github.com/svrooij/node-xiaomi2mqtt/blob/638450a70fe763343aa28f1f89e239cf571ace57/src/bridge.js#L187
https://github.com/svrooij/node-xiaomi2mqtt/blob/638450a70fe763343aa28f1f89e239cf571ace57/src/bridge.js#L188

I prefer string, easy to read and maintain status

**Comment by svrooij** [comment]
Closing before archive, see https://github.com/svrooij/node-xiaomi2mqtt#xiaomi2mqtt
