### ISSUE TITLE
MiHome/Firmware update?

### ISSUE THREAD

**Issue by jonaslt** [svrooij/node-xiaomi2mqtt#11]
It seems it stopped working.

> not handled: {"cmd":"report","model":"gateway","sid":"34ce0091f88b","short_id":0,"data":"{\"rgb\":0,\"illumination\":529}"}
not handled: {"cmd":"report","model":"gateway","sid":"34ce0091f88b","short_id":0,"data":"{\"rgb\":0,\"illumination\":514}"}
not handled: {"cmd":"report","model":"sensor_ht","sid":"158d0001ddb366","short_id":34090,"data":"{\"temperature\":\"1885\"}"}
not handled: {"cmd":"report","model":"sensor_ht","sid":"158d0001ddb366","short_id":34090,"data":"{\"humidity\":\"6595\"}"}
not handled: {"cmd":"report","model":"sensor_switch.aq2","sid":"158d0001b76901","short_id":10905,"data":"{\"status\":\"click\"}"}
not handled: {"cmd":"report","model":"sensor_switch.aq2","sid":"158d0001b76901","short_id":10905,"data":"{\"status\":\"click\"}"}
not handled: {"cmd":"report","model":"sensor_ht","sid":"158d0001ddb366","short_id":34090,"data":"{\"temperature\":\"1893\"}"}
not handled: {"cmd":"report","model":"sensor_ht","sid":"158d0001ddb366","short_id":34090,"data":"{\"humidity\":\"6602\"}"}

**Comment by svrooij** [comment]
Have toch verify this myself, but I'm afraid go update my firmware to check this out.
The code mentioned isn't part of my library but is in the library I use to connect to the gateway.
See here https://github.com/marvinroger/node-lumi-aqara/blob/528d6f701d8ba521bc93f3aaa8fc17c6e3adfdc4/src/index.js#L73
I'm sure it is an issue with the library to connect to the device, can you create an issue there?
