### ISSUE TITLE
Connection to Xiaomi Gateway

### ISSUE THREAD

**Issue by CamzBarber** [svrooij/node-xiaomi2mqtt#12]
Hi,

I am currently getting a 'xiaomi/connected' of '1' due to it not connected to the Xiaomi hardware.

I have enabled developer mode and have the password, however, I have not input this anywhere in xiaomi2mqtt. How do I go about getting the status of '2'?

Thanks!

**Comment by svrooij** [comment]
https://github.com/svrooij/node-xiaomi2mqtt#device-list You can input it through the device list
