### ISSUE TITLE
 How is Xiaomi2mqtt connected to Aquara hardware device

### ISSUE THREAD

**Issue by ghasemikasra39** [svrooij/node-xiaomi2mqtt#14]
Its is not an issue. I had a question but didn't know where to ask.

I've already read the xiaomi2mqtt documentation. What I want to know is that how xiaomi2mqtt is connected to the actual hardware device (Aquara) over the Internet? In another world, I don't understand this part of the documentation:

```
//Device list:

{
  "device_id": "Nice name",
  "158d000aaa2888": "Bedroom window",
  "158d000aaa5b35": "Frontdoor",
  "gateways": {
    "gateway_id": "password"
  }
}
```

> "158d000aaa2888", "158d000aaa5b35, "gateway_id", "password", "device_id"

What are these? Where do they from ? What are they used for?

**Comment by svrooij** [comment]
You'll have to [configure](https://github.com/svrooij/node-xiaomi2mqtt#configure-the-gateway) the gateway. As  describe [here](https://github.com/svrooij/node-xiaomi2mqtt/wiki/Network-mode-iOS).

This way you enable the gateway to multicast all events on your local network. xiaomi2mqqt has to be run on a device on your local network to receive all these events.

The password is retrieved from the app. The device id's can be found in the console when running this program or by loading them from the app.

**Comment by ghasemikasra39** [comment]
But prior to executing the _xiaomi2mqtt_ command, I need to provide the _xiaomi2mqtt.json_ file. In this file it asks for some key-value pairs such as these:

'**device_id**' and '**gateway_id**' (What do you mean by **device**?,  Where can I find these?)
'**158d000aaa5b35**', '**158d000aaa2888**' (What are these numbers?, Where do they come from?)
**password**  (Is it the password I get at the end of [this](https://github.com/svrooij/node-xiaomi2mqtt/wiki/Network-mode-iOS))

**Comment by svrooij** [comment]
This file is optional..... It gives you a way to name the devices....
And when you start this program without it, it will just display the id's in the console.

Please be aware that this program is completely open-source and licensed under MIT. This also means I don't earn anything in supporting it. See the readme for a [paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T9XFJYUSPE4SG) button.

**Comment by ghasemikasra39** [comment]
What would happen if I had multiple gateways with multiple devices connected to each? Would I need the xiaomi2mqtt.json file ? If I would, how should I configure it ?

**Comment by svrooij** [comment]
Please read [this issue](https://github.com/svrooij/node-xiaomi2mqtt/issues/13)
