### ISSUE TITLE
Implementing other sensors

### ISSUE THREAD

**Issue by svrooij** [svrooij/node-xiaomi2mqtt#2]
@TonyFeestneus [requested](https://github.com/svrooij/node-xiaomi2mqtt/issues/1#issuecomment-321345266) other sensors to be implemented.

There is an [update](https://github.com/marvinroger/node-lumi-aqara/pull/6) on the interface package, if that gets released to npm, I will update this package to support the temperature and humidity sensor as well as the motion sensor.

**Comment by svrooij** [comment]
@TonyFeestneus could you verify that those extra sensors now work?

Just do a `git pull && npm install` on the directory where you installed it.

**Comment by TonyFeestneus** [comment]
Sorry, am using a simple python script now which I let push ALL the xiaomi info over mqtt... so then I filter and do stuff with it in other custom scripts. Thanks though!
