### ISSUE TITLE
Enable network mode on iOS

### ISSUE THREAD

**Issue by wsc96** [svrooij/node-xiaomi2mqtt#26]
The settings screen for the hub shows only “Plugin version” and not “Tutorial” or “About” options (per your screenshot) under Shortcut Settings for iOS v4.19.2 of the Mi Home app. I have the Region set to China. 

Can anyone confirm that these instructions are still valid for this version of the iOS app?

**Comment by svrooij** [comment]
Closing before archive, see https://github.com/svrooij/node-xiaomi2mqtt#xiaomi2mqtt
