### ISSUE TITLE
sensors not handled

### ISSUE THREAD

**Issue by jiraff** [svrooij/node-xiaomi2mqtt#3]
Tell me why the sensors are not going to crumble. In the console writes:
Gateway discovered
Light updated: {"color": {"r": 0, "g": 255, "b": 138}, "intensity": 7}
Gateway ready
not handled: {"cmd": "read_ack", "model": "sensor_switch.aq2", "sid": "158d00016c466c", "short_id": 3199, "data": "{\" voltage \ ": 3115} "}
not handled: {"cmd": "read_ack", "model": "weather.v1", "sid": "158d0001d6f398", "short_id": 52425, "data": "{\" voltage \ ": 3075, \ "temperature \": \ "2514 \", \ "humidity \": \ "2909 \", \ "pressure \": \ "103690 \"} "}

local.json:
{
   "mqtt": {
     "host": "mqtt: //localhost: 1883",
     "user": null,
     "password": null
   },
   "gateway": {
       "password": "3e84ixj8qajwcx2d",
       "devices": {
         "158d0001d6f398": "temper"
       }
   }
}

What did I set up wrong?

**Comment by svrooij** [comment]
This library uses an other [library](https://github.com/marvinroger/node-lumi-aqara) for communication with the gateway. Last time there was a delay in the npm release, so I created my own version. Will revert back to the original npm tomorrow for more device support. 

All the devices handled by this application can be found down from [this line](https://github.com/svrooij/node-xiaomi2mqtt/blob/master/index.js#L145).

**Comment by svrooij** [comment]
@jiraff could you check it is fixed with the latest version?

**Comment by svrooij** [comment]
@jiraff this issue was with a previous version of this application, closing this issue.
Please create a new issue if you got a sensor that isn't working.
