### ISSUE TITLE
temperature/humidity/pressure

### ISSUE THREAD

**Issue by soundman666** [svrooij/node-xiaomi2mqtt#5]
Please add a pressure metric for the new Aqara sensor (see getPressure () in node-lumi-aqara)

https://github.com/marvinroger/node-lumi-aqara/commit/05ff1739edd2621c4e21ad3d0e86f958e9834bc4

**Comment by svrooij** [comment]
@soundman666 this is now fixed in the the latest release v1.1.0
could you please test?

**Comment by soundman666** [comment]
Yes, it's works
![image](https://user-images.githubusercontent.com/11494430/34338495-1f643908-e972-11e7-902b-8e8f47db2e4b.png)

**Comment by svrooij** [comment]
YEAH, it works 😄
