### ISSUE TITLE
Multiple Gateways

### ISSUE THREAD

**Issue by bebben88** [svrooij/node-xiaomi2mqtt#8]
I have two gateways in my network. When I start this fine script it keeps disconnecting and connecting between the two. I'm running this in a docker container. I dont know if that produces an issue too.

**Comment by svrooij** [comment]
I didn’t know you could run this app in Docker, because it used multicast to receive info from the gateway(s). And multicast traffic (by default) won’t reach your container.

Implementing more then one gateway is on my list, but I only have one gateway so I cannot test/implement this.

**Comment by bebben88** [comment]
If you use the network host option it works. Well it also works if you open
up udp ports. 224.0.0.50:9898/udp.

Den 30 jan. 2018 10:01 em skrev "Stephan van Rooij" <
notifications@github.com>:

I didn’t know you could run this app in Docker, because it used multicast
to receive info from the gateway(s). And multicast traffic (by default)
won’t reach your container.

Implementing more then one gateway is on my list, but I only have one
gateway so I cannot test/implement this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/svrooij/node-xiaomi2mqtt/issues/8#issuecomment-361732749>,
or mute the thread

**Comment by svrooij** [comment]
@bebben88 could you verify my new version? I cannot test out this version since I don't own a second gateway.

Please re-open if it doesn't work.

**Comment by bebben88** [comment]
Just testing it in a haste before i'll go to sleep, i get some exception, remember i run it in a docker, so i dont know if thats the trouble now. I will test it further in the next day.

dgram.js:614
    throw errnoException(err, 'addMembership');
    ^

Error: addMembership EADDRINUSE
    at _errnoException (util.js:1003:13)
    at Socket.addMembership (dgram.js:614:11)
    at Socket.Aqara._serverSocket.on (/usr/src/app/node_modules/lumi-aqara/src/index.js:22:32)
    at Socket.emit (events.js:160:13)
    at startListening (dgram.js:156:10)
    at _handle.lookup (dgram.js:273:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
