### ISSUE TITLE
Getting luminescence from human body sensor

### ISSUE THREAD

**Issue by adamoliver78** [svrooij/node-xiaomi2mqtt#9]
Hi,

I've been using this too for a while with basic gateway, switches and temperature sensor with great success. Excellent work!

I just got hold of the xiaomi human body sensor, which has a built in lux sensor. If a use one of the other node-red plugins (e.g. xiaomi smart home), when motion is triggered there are two outputs from the gateway - one for motion/no-motion, and one for lux.

Using xiaomi2mqtt, and monitoring using "mosquitto_sub -t "#" -v", the only output I see is when motion is triggered. Is it possible to get the lux value as well?

Happy to assist with testing / debugging - let me know if there's any information I can provide.
Thanks.

**Comment by svrooij** [comment]
I think I can get this to work, as it says in the lumi-aqara the lux sensor is supported.
Don’t have the new sensor (still in the box) here, but will get it to work anyway.

Just hang on a little bit.

Do you know if the lux value changes if the detection doesn’t? So if you get different lux values without movement?

**Comment by adamoliver78** [comment]
That would be great. No rush.

From what I can tell, it only reports lux when movement is detected, based
on some quick tests.

**Comment by svrooij** [comment]
@adamoliver78 could you verify this new version is working?

If it doesn't work please reopen this issue.

**Comment by adamoliver78** [comment]
@svrooij 
Looks like you've cracked it. I haven't tested the lux variation extensively yet, but it varies when moved between light and dark rooms as you can see below. 

Some debug output for your info:
{"val":"no_motion","battery":45,"name":"testmotion","ts":1517833176860,"secondsSinceMotion":"300","lux":"68"}
{"val":"motion","battery":45,"name":"testmotion","ts":1517832727950,"lux":"10"}
{"val":"motion","battery":45,"name":"testmotion","ts":1517832816834,"lux":"13"}
{"val":"motion","battery":45,"name":"testmotion","ts":1517833570604,"lux":"53"}

Thanks for the quick turnaround.
